### ISSUE TITLE
Nebula not compatible with version 0.10.28.x

### ISSUE THREAD

**Issue by DerFl3x** [NebulaModTeam/nebula#644] opened 2024-01-13 18:02 UTC
Getting error code that Nebula isnt compatible. 
seems like this can only be fixed with downgrading the game version.
thanks alot :)

**Comment by Dessix** [comment] 2024-01-16 03:17
This is likely a duplicate of #617. While that issue has not been updated after the merger of #616, it looks like it should at least be a lot closer now than it was.

**Closed** 2024-02-18 20:48 UTC
